export const FILTERED = [
  "__defineGetter__",
  "__defineSetter__",
  "__lookupGetter__",
  "__lookupSetter__",
  "__proto__",
  "arguments",
  "caller",
  "prototype"
]

// undefined
// null
export const DATATYPES = {
  "Boolean": true,
  "Number": 5,
  "BigInt": 5n,
  "String": "test",
  "Symbol": Symbol("id"),
  "Object": new Object(),
  "Function": new Function(),
  "Array": [],
  "Map": new Map(),
  "WeakMap": new WeakMap(),
  "Set": new Set(),
  "WeakSet": new WeakSet(),
  "Date": new Date(),
  "RegExp": new RegExp(),
  "Promise": Promise.resolve(),
  "Error": new Error(),
  "FormData": new FormData(),
  "Image": new Image(),
  "Audio": new Audio(),
  "Proxy": new Proxy(new Object(), () => {}),
  "JSON": JSON,
  "Math": Math,
  "WebSocket": new WebSocket(""),
  "URL": URL,
  "Blob": new Blob(),
  "XMLHttpRequest": new XMLHttpRequest(),
  "Document": new Document(),
  "Event": new Event("click"),
  "CustomEvent": new CustomEvent("a"),
  "AbortController": new AbortController(),
  "MutationObserver": new MutationObserver(() => {}),
  "ResizeObserver": new ResizeObserver(() => {}),
  "IntersectionObserver": new IntersectionObserver(() => {}),
  "PerformanceObserver": new PerformanceObserver(() => {}),
  "Notification": new Notification(""),
  "URLSearchParams": new URLSearchParams(),
  "HTMLScriptElement": document.createElement("script"),
  "Element": document.createElement("element"),
  "Headers": new Headers(),
  "Request": new Request(""),
  "Response": new Response(),
  "DOMParser": new DOMParser(),
  "FileReader": new FileReader(),
  "TextEncoder": new TextEncoder(),
  "TextDecoder": new TextDecoder(),
  "MediaStream": new MediaStream(),
  "AudioContext": new AudioContext(),
  "DOMRect": new DOMRect(),
  "CSSStyleSheet": new CSSStyleSheet(),
  "Navigator": null,
  "HTMLTableElement": document.createElement("table")
};
